version: "3"
services:
  
  back:
    build:
      context: ./docker
      dockerfile: Dockerfile
    ports:
      - 8090:8090
    container_name: java-back
    networks:
      con-full-stack:
        ipv4_address: 10.5.0.5
    volumes:
      - ./api/src:/usr/app/src

  front:
    build:
      context: ./src/main/ui
      dockerfile: Dockerfile
    ports:
      -  4200:4200
    container_name: angular-front
    networks:
      -  con-full-stack
    depends_on:
      - back
    stdin_open: true
    tty: true
  

networks:
  con-full-stack:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1

volumes:
  db_data: {}